name: Build
on: [pull_request, push]

jobs:
  debug-builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upgrading the Wrapper version
        run: | 
             ./gradlew wrapper --gradle-version 7.5.1 --distribution-type all
             ./gradlew wrapper --gradle-version 7.5.1 --distribution-type all
      - name: Verify the checksum of the Wrapper JAR
        run: |
             cd gradle/wrapper
             curl --location --output gradle-wrapper.jar.sha256 \
                  https://services.gradle.org/distributions/gradle-7.5.1-wrapper.jar.sha256
             echo "  gradle-wrapper.jar" >> gradle-wrapper.jar.sha256
             sha256sum --check gradle-wrapper.jar.sha256
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 1
          distribution: "temurin"
          cache: 'gradle'
      - name: Build debug APK and run jvm tests
        run: ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: app/build/outputs/apk/debug/*.apk
